## -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MusicSort.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import musicSort_Module

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MusicSort")
        MainWindow.resize(600, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OutText = QtWidgets.QLineEdit(self.centralwidget)
        self.OutText.setGeometry(QtCore.QRect(110, 110, 310, 20))
        self.OutText.setObjectName("OutText")
        self.Out = QtWidgets.QPushButton(self.centralwidget)
        self.Out.setGeometry(QtCore.QRect(430, 110, 75, 23))
        self.Out.setObjectName("Out")
        self.InText = QtWidgets.QLineEdit(self.centralwidget)
        self.InText.setGeometry(QtCore.QRect(110, 50, 310, 20))
        self.InText.setObjectName("InText")
        self.In = QtWidgets.QPushButton(self.centralwidget)
        self.In.setGeometry(QtCore.QRect(430, 50, 75, 23))
        self.In.setObjectName("In")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(440, 170, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 170, 76, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.In.clicked.connect(MainWindow.InPath)
        self.Out.clicked.connect(MainWindow.OutPath)
        self.buttonBox.accepted.connect(MainWindow.Accept)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def InPath(self):
        inpath = QtWidgets.QFileDialog.getExistingDirectory(self,'Open Folder')
        self.InText.setText(inpath)

    def OutPath(self):
        OutPath = QtWidgets.QFileDialog.getExistingDirectory(self,'Open Folder')
        self.OutText.setText(OutPath)

    def Accept(self):
        if self.InText.text() == "" or self.OutText.text() == "":
            print("경로를 지정해주세요!!")
        else:
            musicSort_Module.MusicSort(self.InText.text(),self.OutText.text(),self.comboBox.currentText())
            print("끝!")
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MusicSort", "MusicSort"))
        self.Out.setText(_translate("MainWindow", "Export"))
        self.In.setText(_translate("MainWindow", "Import"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ARTIST"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ALBUM"))
        self.comboBox.setItemText(2, _translate("MainWindow", "DATE"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
